services:
  krisp-apm:
    build:
      context: .
      dockerfile: Dockerfile
    image: caretalk/krisp-apm:v1
    container_name: caretalk-krisp-apm
    ports:
      - "3344:3344"
    restart: unless-stopped
    command: [ "3344", "krisp/models/inb.bvc.hs.c6.w.s.23cdb3.kef", "10", "120"]
